/**
* @DisplayName GetData
* @summary it returns the object for Data
* @returns {object} Data
*/
export const GetData = () => {
    let SuggestionData = [
        { "DisplayName": "Afghanistan", "Id": "AF" },
        { "DisplayName": "Åland Islands", "Id": "AX" },
        { "DisplayName": "Albania", "Id": "AL" },
        { "DisplayName": "Algeria", "Id": "DZ" },
        { "DisplayName": "American Samoa", "Id": "AS" },
        { "DisplayName": "AndorrA", "Id": "AD" },
        { "DisplayName": "Angola", "Id": "AO" },
        { "DisplayName": "Anguilla", "Id": "AI" },
        { "DisplayName": "Antarctica", "Id": "AQ" },
        { "DisplayName": "Antigua and Barbuda", "Id": "AG" },
        { "DisplayName": "Argentina", "Id": "AR" },
        { "DisplayName": "Armenia", "Id": "AM" },
        { "DisplayName": "Aruba", "Id": "AW" },
        { "DisplayName": "Australia", "Id": "AU" },
        { "DisplayName": "Austria", "Id": "AT" },
        { "DisplayName": "Azerbaijan", "Id": "AZ" },
        { "DisplayName": "Bahamas", "Id": "BS" },
        { "DisplayName": "Bahrain", "Id": "BH" },
        { "DisplayName": "Bangladesh", "Id": "BD" },
        { "DisplayName": "Barbados", "Id": "BB" },
        { "DisplayName": "Belarus", "Id": "BY" },
        { "DisplayName": "Belgium", "Id": "BE" },
        { "DisplayName": "Belize", "Id": "BZ" },
        { "DisplayName": "Benin", "Id": "BJ" },
        { "DisplayName": "Bermuda", "Id": "BM" },
        { "DisplayName": "Bhutan", "Id": "BT" },
        { "DisplayName": "Bolivia", "Id": "BO" },
        { "DisplayName": "Bosnia and Herzegovina", "Id": "BA" },
        { "DisplayName": "Botswana", "Id": "BW" },
        { "DisplayName": "Bouvet Island", "Id": "BV" },
        { "DisplayName": "Brazil", "Id": "BR" },
        { "DisplayName": "British Indian Ocean Territory", "Id": "IO" },
        { "DisplayName": "Brunei Darussalam", "Id": "BN" },
        { "DisplayName": "Bulgaria", "Id": "BG" },
        { "DisplayName": "Burkina Faso", "Id": "BF" },
        { "DisplayName": "Burundi", "Id": "BI" },
        { "DisplayName": "Cambodia", "Id": "KH" },
        { "DisplayName": "Cameroon", "Id": "CM" },
        { "DisplayName": "Canada", "Id": "CA" },
        { "DisplayName": "Cape Verde", "Id": "CV" },
        { "DisplayName": "Cayman Islands", "Id": "KY" },
        { "DisplayName": "Central African Republic", "Id": "CF" },
        { "DisplayName": "Chad", "Id": "TD" },
        { "DisplayName": "Chile", "Id": "CL" },
        { "DisplayName": "China", "Id": "CN" },
        { "DisplayName": "Christmas Island", "Id": "CX" },
        { "DisplayName": "Cocos (Keeling) Islands", "Id": "CC" },
        { "DisplayName": "Colombia", "Id": "CO" },
        { "DisplayName": "Comoros", "Id": "KM" },
        { "DisplayName": "Congo", "Id": "CG" },
        { "DisplayName": "Congo, The Democratic Republic of the", "Id": "CD" },
        { "DisplayName": "Cook Islands", "Id": "CK" },
        { "DisplayName": "Costa Rica", "Id": "CR" },
        { "DisplayName": "Croatia", "Id": "HR" },
        { "DisplayName": "Cuba", "Id": "CU" },
        { "DisplayName": "Cyprus", "Id": "CY" },
        { "DisplayName": "Czech Republic", "Id": "CZ" },
        { "DisplayName": "Denmark", "Id": "DK" },
        { "DisplayName": "Djibouti", "Id": "DJ" },
        { "DisplayName": "Dominica", "Id": "DM" },
        { "DisplayName": "Dominican Republic", "Id": "DO" },
        { "DisplayName": "Ecuador", "Id": "EC" },
        { "DisplayName": "Egypt", "Id": "EG" },
        { "DisplayName": "El Salvador", "Id": "SV" },
        { "DisplayName": "Equatorial Guinea", "Id": "GQ" },
        { "DisplayName": "Eritrea", "Id": "ER" },
        { "DisplayName": "Estonia", "Id": "EE" },
        { "DisplayName": "Ethiopia", "Id": "ET" },
        { "DisplayName": "Falkland Islands (Malvinas)", "Id": "FK" },
        { "DisplayName": "Faroe Islands", "Id": "FO" },
        { "DisplayName": "Fiji", "Id": "FJ" },
        { "DisplayName": "Finland", "Id": "FI" },
        { "DisplayName": "France", "Id": "FR" },
        { "DisplayName": "French Guiana", "Id": "GF" },
        { "DisplayName": "French Polynesia", "Id": "PF" },
        { "DisplayName": "French Southern Territories", "Id": "TF" },
        { "DisplayName": "Gabon", "Id": "GA" },
        { "DisplayName": "Gambia", "Id": "GM" },
        { "DisplayName": "Georgia", "Id": "GE" },
        { "DisplayName": "Germany", "Id": "DE" },
        { "DisplayName": "Ghana", "Id": "GH" },
        { "DisplayName": "Gibraltar", "Id": "GI" },
        { "DisplayName": "Greece", "Id": "GR" },
        { "DisplayName": "Greenland", "Id": "GL" },
        { "DisplayName": "Grenada", "Id": "GD" },
        { "DisplayName": "Guadeloupe", "Id": "GP" },
        { "DisplayName": "Guam", "Id": "GU" },
        { "DisplayName": "Guatemala", "Id": "GT" },
        { "DisplayName": "Guernsey", "Id": "GG" },
        { "DisplayName": "Guinea", "Id": "GN" },
        { "DisplayName": "Guinea-Bissau", "Id": "GW" },
        { "DisplayName": "Guyana", "Id": "GY" },
        { "DisplayName": "Haiti", "Id": "HT" },
        { "DisplayName": "Heard Island and Mcdonald Islands", "Id": "HM" },
        { "DisplayName": "Holy See (Vatican City State)", "Id": "VA" },
        { "DisplayName": "Honduras", "Id": "HN" },
        { "DisplayName": "Hong Kong", "Id": "HK" },
        { "DisplayName": "Hungary", "Id": "HU" },
        { "DisplayName": "Iceland", "Id": "IS" },
        { "DisplayName": "India", "Id": "IN" },
        { "DisplayName": "Indonesia", "Id": "ID" },
        { "DisplayName": "Iran, Islamic Republic Of", "Id": "IR" },
        { "DisplayName": "Iraq", "Id": "IQ" },
        { "DisplayName": "Ireland", "Id": "IE" },
        { "DisplayName": "Isle of Man", "Id": "IM" },
        { "DisplayName": "Israel", "Id": "IL" },
        { "DisplayName": "Italy", "Id": "IT" },
        { "DisplayName": "Jamaica", "Id": "JM" },
        { "DisplayName": "Japan", "Id": "JP" },
        { "DisplayName": "Jersey", "Id": "JE" },
        { "DisplayName": "Jordan", "Id": "JO" },
        { "DisplayName": "Kazakhstan", "Id": "KZ" },
        { "DisplayName": "Kenya", "Id": "KE" },
        { "DisplayName": "Kiribati", "Id": "KI" },
        { "DisplayName": "Korea, Republic of", "Id": "KR" },
        { "DisplayName": "Kuwait", "Id": "KW" },
        { "DisplayName": "Kyrgyzstan", "Id": "KG" },
        { "DisplayName": "Latvia", "Id": "LV" },
        { "DisplayName": "Lebanon", "Id": "LB" },
        { "DisplayName": "Lesotho", "Id": "LS" },
        { "DisplayName": "Liberia", "Id": "LR" },
        { "DisplayName": "Libyan Arab Jamahiriya", "Id": "LY" },
        { "DisplayName": "Liechtenstein", "Id": "LI" },
        { "DisplayName": "Lithuania", "Id": "LT" },
        { "DisplayName": "Luxembourg", "Id": "LU" },
        { "DisplayName": "Macao", "Id": "MO" },
        { "DisplayName": "Macedonia, The Former Yugoslav Republic of", "Id": "MK" },
        { "DisplayName": "Madagascar", "Id": "MG" },
        { "DisplayName": "Malawi", "Id": "MW" },
        { "DisplayName": "Malaysia", "Id": "MY" },
        { "DisplayName": "Maldives", "Id": "MV" },
        { "DisplayName": "Mali", "Id": "ML" },
        { "DisplayName": "Malta", "Id": "MT" },
        { "DisplayName": "Marshall Islands", "Id": "MH" },
        { "DisplayName": "Martinique", "Id": "MQ" },
        { "DisplayName": "Mauritania", "Id": "MR" },
        { "DisplayName": "Mauritius", "Id": "MU" },
        { "DisplayName": "Mayotte", "Id": "YT" },
        { "DisplayName": "Mexico", "Id": "MX" },
        { "DisplayName": "Micronesia, Federated States of", "Id": "FM" },
        { "DisplayName": "Moldova, Republic of", "Id": "MD" },
        { "DisplayName": "Monaco", "Id": "MC" },
        { "DisplayName": "Mongolia", "Id": "MN" },
        { "DisplayName": "Montserrat", "Id": "MS" },
        { "DisplayName": "Morocco", "Id": "MA" },
        { "DisplayName": "Mozambique", "Id": "MZ" },
        { "DisplayName": "Myanmar", "Id": "MM" },
        { "DisplayName": "Namibia", "Id": "NA" },
        { "DisplayName": "Nauru", "Id": "NR" },
        { "DisplayName": "Nepal", "Id": "NP" },
        { "DisplayName": "Netherlands", "Id": "NL" },
        { "DisplayName": "Netherlands Antilles", "Id": "AN" },
        { "DisplayName": "New Caledonia", "Id": "NC" },
        { "DisplayName": "New Zealand", "Id": "NZ" },
        { "DisplayName": "Nicaragua", "Id": "NI" },
        { "DisplayName": "Niger", "Id": "NE" },
        { "DisplayName": "Nigeria", "Id": "NG" },
        { "DisplayName": "Niue", "Id": "NU" },
        { "DisplayName": "Norfolk Island", "Id": "NF" },
        { "DisplayName": "Northern Mariana Islands", "Id": "MP" },
        { "DisplayName": "Norway", "Id": "NO" },
        { "DisplayName": "Oman", "Id": "OM" },
        { "DisplayName": "Pakistan", "Id": "PK" },
        { "DisplayName": "Palau", "Id": "PW" },
        { "DisplayName": "Palestinian Territory, Occupied", "Id": "PS" },
        { "DisplayName": "Panama", "Id": "PA" },
        { "DisplayName": "Papua New Guinea", "Id": "PG" },
        { "DisplayName": "Paraguay", "Id": "PY" },
        { "DisplayName": "Peru", "Id": "PE" },
        { "DisplayName": "Philippines", "Id": "PH" },
        { "DisplayName": "Pitcairn", "Id": "PN" },
        { "DisplayName": "Poland", "Id": "PL" },
        { "DisplayName": "Portugal", "Id": "PT" },
        { "DisplayName": "Puerto Rico", "Id": "PR" },
        { "DisplayName": "Qatar", "Id": "QA" },
        { "DisplayName": "Reunion", "Id": "RE" },
        { "DisplayName": "Romania", "Id": "RO" },
        { "DisplayName": "Russian Federation", "Id": "RU" },
        { "DisplayName": "RWANDA", "Id": "RW" },
        { "DisplayName": "Saint Helena", "Id": "SH" },
        { "DisplayName": "Saint Kitts and Nevis", "Id": "KN" },
        { "DisplayName": "Saint Lucia", "Id": "LC" },
        { "DisplayName": "Saint Pierre and Miquelon", "Id": "PM" },
        { "DisplayName": "Saint Vincent and the Grenadines", "Id": "VC" },
        { "DisplayName": "Samoa", "Id": "WS" },
        { "DisplayName": "San Marino", "Id": "SM" },
        { "DisplayName": "Sao Tome and Principe", "Id": "ST" },
        { "DisplayName": "Saudi Arabia", "Id": "SA" },
        { "DisplayName": "Senegal", "Id": "SN" },
        { "DisplayName": "Serbia and Montenegro", "Id": "CS" },
        { "DisplayName": "Seychelles", "Id": "SC" },
        { "DisplayName": "Sierra Leone", "Id": "SL" },
        { "DisplayName": "Singapore", "Id": "SG" },
        { "DisplayName": "Slovakia", "Id": "SK" },
        { "DisplayName": "Slovenia", "Id": "SI" },
        { "DisplayName": "Solomon Islands", "Id": "SB" },
        { "DisplayName": "Somalia", "Id": "SO" },
        { "DisplayName": "South Africa", "Id": "ZA" },
        { "DisplayName": "South Georgia and the South Sandwich Islands", "Id": "GS" },
        { "DisplayName": "Spain", "Id": "ES" },
        { "DisplayName": "Sri Lanka", "Id": "LK" },
        { "DisplayName": "Sudan", "Id": "SD" },
        { "DisplayName": "SuriDisplayName", "Id": "SR" },
        { "DisplayName": "Svalbard and Jan Mayen", "Id": "SJ" },
        { "DisplayName": "Swaziland", "Id": "SZ" },
        { "DisplayName": "Sweden", "Id": "SE" },
        { "DisplayName": "Switzerland", "Id": "CH" },
        { "DisplayName": "Syrian Arab Republic", "Id": "SY" },
        { "DisplayName": "Taiwan, Province of China", "Id": "TW" },
        { "DisplayName": "Tajikistan", "Id": "TJ" },
        { "DisplayName": "Tanzania, United Republic of", "Id": "TZ" },
        { "DisplayName": "Thailand", "Id": "TH" },
        { "DisplayName": "Timor-Leste", "Id": "TL" },
        { "DisplayName": "Togo", "Id": "TG" },
        { "DisplayName": "Tokelau", "Id": "TK" },
        { "DisplayName": "Tonga", "Id": "TO" },
        { "DisplayName": "Trinidad and Tobago", "Id": "TT" },
        { "DisplayName": "Tunisia", "Id": "TN" },
        { "DisplayName": "Turkey", "Id": "TR" },
        { "DisplayName": "Turkmenistan", "Id": "TM" },
        { "DisplayName": "Turks and Caicos Islands", "Id": "TC" },
        { "DisplayName": "Tuvalu", "Id": "TV" },
        { "DisplayName": "Uganda", "Id": "UG" },
        { "DisplayName": "Ukraine", "Id": "UA" },
        { "DisplayName": "United Arab Emirates", "Id": "AE" },
        { "DisplayName": "United Kingdom", "Id": "GB" },
        { "DisplayName": "United States", "Id": "US" },
        { "DisplayName": "United States Minor Outlying Islands", "Id": "UM" },
        { "DisplayName": "Uruguay", "Id": "UY" },
        { "DisplayName": "Uzbekistan", "Id": "UZ" },
        { "DisplayName": "Vanuatu", "Id": "VU" },
        { "DisplayName": "Venezuela", "Id": "VE" },
        { "DisplayName": "Viet Nam", "Id": "VN" },
        { "DisplayName": "Virgin Islands, British", "Id": "VG" },
        { "DisplayName": "Virgin Islands, U.S.", "Id": "VI" },
        { "DisplayName": "Wallis and Futuna", "Id": "WF" },
        { "DisplayName": "Western Sahara", "Id": "EH" },
        { "DisplayName": "Yemen", "Id": "YE" },
        { "DisplayName": "Zambia", "Id": "ZM" },
        { "DisplayName": "Zimbabwe", "Id": "ZW" }
    ]  //Suggestion Data to control.

    return {
        SuggestionData,
        //SelectedValue: "YE", //pre select value.
    };
};